[package]
name = "iso-tp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-hal = { path = "../async-hal" }
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
