[package]
name = "iso-tp"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Async ISO-TP (ISO 15765-2) implementation for embedded devices"
repository = "https://github.com/matthunz/async-hal"

[dependencies]
async-hal =  "0.1.0-alpha.8"
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
